version: "3"

services:
  app:
    container_name: ratelimiter
    build: .
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - ./.env:/.env
    depends_on:
      - redis
    networks:
      - ratelimiter

  redis:
    image: redis:6.2-alpine
    container_name: redis
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_USERNAME=${REDIS_USERNAME}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data
    networks:
      - ratelimiter

networks:
  ratelimiter:
    driver: bridge
